name: Godot CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download Godot
      run: |
        wget https://downloads.tuxfamily.org/godotengine/4.2.1/Godot_v4.2.1-stable_linux_headless.64.zip
        unzip Godot_v4.2.1-stable_linux_headless.64.zip
        chmod +x Godot_v4.2.1-stable_linux_headless.64
    - name: Run tests
      run: ./Godot_v4.2.1-stable_linux_headless.64 -d -s --path . addons/gut/gut_cmdln.gd
